### ISSUE TITLE
Scientific Illustration

### ISSUE THREAD

**Issue by YongLD** [maklachur/Mamba-in-Computer-Vision#1]
What an excellent review paper! I would like to ask which software you used to create the figures in your paper—they look fantastic!
![image](https://github.com/user-attachments/assets/5493f088-6b53-46b6-a664-3b5d14473d10)
![image](https://github.com/user-attachments/assets/b979a02a-5384-413c-be46-8fb076bca54b)

**Comment by maklachur** [comment]
Thank you for your query. We appreciate that you enjoyed our work. For the taxonomy figure, we used MS PowerPoint, while for the comparison figures, we plotted them using coding, mostly using Matplotlib in Python. I hope this helps!
